delete from datavalueaudit where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from datavalue where sourceid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from trackedentitydatavalueaudit where programstageinstanceid in(select programstageinstanceid from  programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%'));
delete from datasetsource where sourceid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from completedatasetregistration where sourceid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from program_organisationunits where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from programmessage where programstageinstanceid in(select programstageinstanceid from  programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%')); 
delete from programstageinstancecomments where programstageinstanceid in(select programstageinstanceid from  programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%')); 
-- delete from programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from programstageinstance where programinstanceid in(select programinstanceid from programinstance where trackedentityinstanceid in(select trackedentityinstanceid from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%')));
delete from trackedentitydatavalue where programstageinstanceid in(select programstageinstanceid from  programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%'));
delete from trackedentityattributevalueaudit where trackedentityinstanceid in(select trackedentityinstanceid from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%'));
delete from trackedentityattributevalue where trackedentityinstanceid in(select trackedentityinstanceid from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%'));
-- delete from programinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from programinstance where trackedentityinstanceid in(select trackedentityinstanceid from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%'));
delete from programownershiphistory where trackedentityinstanceid in(select trackedentityinstanceid from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%'));
-- delete from trackedentityprogramowner where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from trackedentityprogramowner where trackedentityinstanceid in(select trackedentityinstanceid from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%'));
delete from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from categoryoption_organisationunits where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from usermembership where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from orgunitgroupmembers where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from visualization_organisationunits where organisationunitid in(select organisationunitid from organisationunit where path ilike '%jbq5nGwudFM%');
delete from organisationunit where path ilike '%jbq5nGwudFM%';