delete from datavalueaudit where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from datavalue where sourceid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from trackedentitydatavalueaudit where programstageinstanceid in(select programstageinstanceid from  programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%'));
delete from datasetsource where sourceid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from completedatasetregistration where sourceid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from program_organisationunits where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from programmessage where programstageinstanceid in(select programstageinstanceid from  programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%')); 
delete from programstageinstancecomments where programstageinstanceid in(select programstageinstanceid from  programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%')); 
delete from programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from trackedentitydatavalue where programstageinstanceid in(select programstageinstanceid from  programstageinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%'));
delete from trackedentityattributevalueaudit where trackedentityinstanceid in(select trackedentityinstanceid from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%'));
delete from trackedentityattributevalue where trackedentityinstanceid in(select trackedentityinstanceid from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%'));
delete from programinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from trackedentityprogramowner where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from trackedentityinstance where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from categoryoption_organisationunits where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from usermembership where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from orgunitgroupmembers where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from visualization_organisationunits where organisationunitid in(select organisationunitid from organisationunit where path ilike '%vMMvZfLtNus%');
delete from organisationunit where path ilike '%vMMvZfLtNus%';